### ISSUE TITLE
add and remove metaData plots

### ISSUE THREAD

**Issue by grahampullan** [grahampullan/dbslice#11]
- Try using (https://boxicons.com/usage)
- Plus icon in plotRow header
- Launches a modal (https://getbootstrap.com/docs/5.0/components/modal/) - this is a form to populate the necessary data and layout objects. Also needs bar / histogram / scatter dropdown.
- Then remove plot icon in plotTitle.

**Comment by aljazkotnik** [comment]
Hi Graham,

I've been working on the plot removal/addition. When removing a plot there are some side effects due to the D3 approach to plot making/updating/removing.

Issues are:
  - Plots may paste their graphics over other graphics. E.g.: in a sequence of bar, bar, scatter, histogram (from test/session.json), if a bar chart is removed the new scatterplot will have a bar chart in the background.
  - Histograms may throw an error when being updated.  E.g.: in a sequence of bar, bar, scatter, histogram (from test/session.json), if any bar/scatter chart is removed the histogram will break because it cannot find "xDomMin" and "xDomMax", and hterefore cannot construct its bins.
  - Because all plots make use of makeNewPlot, where the remove button was implemented, all plots can be removed - including the contour small multiples!

The issues arise because of how our D3 approach pairs up the data to the HTML elements, and arises only only when changing the plot/plot row data. 

When a plot in the middle of the plot row is removed, its plotData is removed from dbslice.session, and `update' is called to refresh the session. Within the changed plot row, D3 will pair the plotData objects to <div.plot> in sequence, meaning that the plotData after the removed plot move to the preceding <div.plot> and its content. In short: the desired plotData is removed, but the HTML removed is that of the last plot. This then causes the overlap in the graphics. In contour plots the data moves between small multiples, but the title is not updated. The issue with the histogram occurs as the histogram saves the "xDomMin" and "xDomMax" as an attribute of an <svg> <g> element, which is not available after the plot migrates to another <div.plot>.

To fix the graphics overlapping problem the plots have to be cleared everytime the plots, and possibly plot rows, are removed. For histogram issues the histogram would have to be changed to not rely on attributes of the HTML or SVG elements. Furthermore, when plots are migrating between <div.plot> the remove plot functionality has to be refreshed to get access to the correct plotData.

**Comment by aljazkotnik** [comment]
A more elegant approach may be to restructure the plots and the plot adding/removing approach. This could be useful also when implementing the ability to allow the user to change the plotted variables (I already wrote some modules that allow this).


in update.js:


function update( elementId = dbsliceData.elementId, session = dbsliceData.session ){
   
   ...
   
   let plotRows = dbslice.session.plotRows;
   
   // Filter out plots that need to be removed.
   plotRows = plotRows.filter(p=>{
        if(!p.active){
		   p.remove( ... )
		}
		return p.active
   })
   
   
   // Make new plots and update exsiting ones.
   dbslice.session.plotRows.forEach(p=>{
       if(p.node){
	       p.update( ... )
	   } else {
	       p.make( ... )
		   container.appendChild( p.node )
	   } // if
   })
   
   ...
   
} // update



Plot rows can be introduced as a separate object:

const plotRow = {
    make: function(){...},
	update: function(){...},
	remove: function(){...}
}



Plots can be expanded to take control of their HTML and other data, which is useful also when obtaining plotConfigs, as different plots can respond with different types of plot configs.

const cfD3Plot = {
	
	node : undefined,
	
	xDomMin : undefined,
	xDomMax : undefined,

	make : function(){ 
		...
		-- var container = d3.select(element);
		
		...
		
		-- var svg = container.append("svg")
        --  .attr("width", svgWidth)
        --  .attr("height", svgHeight)
		
		++ this.node = d3.create("svg")
        ++  .attr("width", svgWidth)
        ++  .attr("height", svgHeight)
		++  .node()
		
		// Within an object "this" is the parent object.
		
		...
		
		// Keep track of plot specific values
		var xDomMax = itemExtent[1] + 0.05*itemRange; 
        -- plotArea.attr( "xDomMax", xDomMax);
		++ this.xDomMax = xDomMax;
		
		... 
	
	},
	
	update : function(){ ... }
} // cfD3Plot
